services:
  - type: web
    name: procoachvirtual-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: procoachvirtual-db
          property: connectionString
    autoDeploy: true

databases:
  - name: procoachvirtual-db
    databaseName: procoachvirtual
    user: procoachvirtual
